# URL
baseurl: "/"
url: "https://parkraum.osm-verkehrswende.de"

# Content
# Also used for Social Sharing https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
locale: de_DE
title: Parkraum Projekt — OpenStreetMap Verkehrswende
description: Spezialkarten für Neukölln zum Straßenraum und zur Parkplatzdichte.
author: Tobias Jordans
logo: /images/openstreetmap-osm-logo.png
image:
  path: /images/social-sharing.png
  alt: Daten zu Parkplätzen, berechnet auf Basis von OpenStreetMap Daten.
twitter:
  username: "@osmberlin"
  card: summary_large_image

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y-%m-%d"

# Build settings

permalink: /posts/:year-:month-:day-:title

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..3
  parse_block_html: true

theme: minima

# We do not want the TailwindCSS Source File to be looked at by Jekyll
exclude: ["css-src"]
